sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install: 
  - pip install tox-travis
  - version="1.0.1" #For GitHub
  - export version
  - TRAVIS_TAG="v$version"
  - echo "$TRAVIS_TAG"
  - echo "$TRAVIS_COMMIT"
  - echo "$TRAVIS_BUILD_NUMBER"
#  - git tag $TRAVIS_TAG $TRAVIS_COMMIT
# Prepare Items for GitHub Release
  - mkdir ./gitpub # Create Storage Location for future ZIP file
script: tox
before_deploy:
  - export RELEASE_PKG_FILE="./dist/interfax-$version.zip"
  - python setup.py sdist --formats=zip -k # Generate ZIP for GitHub Release
  - mv $RELEASE_PKG_FILE ./gitpub # Move package so PyPi does not upload ZIP on deploy
  - export RELEASE_PKG_FILE="./gitpub/interfax-$version.zip" #File Reference for GitHub Deploy
deploy:
-  provider: pypi
#   server: https://test.pypi.org/legacy/ # Remove for deployment to official PyPi repo
   username: "__token__"
   password:
     secure: sWcfMokMqKqKMO3WZUkS8NFEuNgAjrV5LBf5IJwxvbFmAROd5ZGvESN3tY5PyrVC8UXxipQFeZuco7tMgFMNh1lON467Qg5TFEUBZAZo0h6WOzeuxkSDREShrTZJ50HGOQB+D7uKwcCYmRqBazrF7v6RiVpWCaNMVTfjk0/Si2A6Zaxn8g2psgxrywOZHHZZAo/HT5aJc9uQSLCX13ZGpnfQzyVw5dvBmzSVTB32GnmWGbVVJFmJL9v26FSo2ykDf3hXCwo7uRcod/JgSw5vDN7DHk0dU/Ypkz1fMwJl5u5yZKdqKeO3csBTlJHb7pUjRtTaLdD0KkwmjRnee4SJ79HgwVQSMmDuc42jopBrEZ//dfoqoNwhj6TROm1XDU7MzhvfSVzm/ist+2UrASrWt3ap0nj+nz7NxlL2rsw9hbPl0hv7Rr/MIazEnjeN96xnO0wITOMK9Vy1ed5RIcs88QjPsziuJC0uYDddByCbiLl6yXL07eOTui1r70arBZq4DdVjvw54UwlDouTB6Y85tpOEVcn+1tTdND31LZqrIEk84nUZxbcLFcWo4+QfZEnJPi2Y2sPZYHjhNcEsUxJ4qjXV2BO/2Lnyj2v5T4jBvv1tVrnrPLZ4ChkPMynA4Z5ER/ktA8cbjT1C8u+cGoOPys76aKPbdvUSdvFJLaFUF10=
   distributions: "sdist bdist_wheel"
   skip_existing: true
   skip_cleanup: true
   on:
     tags: true
     condition: $TRAVIS_PYTHON_VERSION == 3.9
-  provider: releases
   api_key:
     secure: S97Yef7wt2WmOkK0W+FhTQrSwjAHoJLLAa2yI4gwNGwg2Vzna9SLEZqynKx8VZi0dkf/jhKBV4Un7PtqzVDaym6IaYwCZ0kICRMbL67Iv/jXlHa1OuQKkwrGzNJJCaPqrz5JLVRQNq+Uu0B4O13BN62n4KverflfZUo7Olt0KrQGmk3YcuQ4mZclDbHii+03TXcXF64qApJNXcTsQh+Y8wusmlVgjwhUN8J5xLn35eAX+Dt5GSHo4V/lW4lWxwVhp35ibaezSb32O3Zlug83bitMteoULK/bg0DZhcLhHkqaNzJgvYTeJDaffueYNEKHDSAq6OVO6QgfREUOj9JJxV0cr9lAuPS2DhW63tpjct1bLA9O2kXgz3yJSWFrbHYYlplUMb5OQJz41SCU326V4fJc+F2GxabbfqBJ8C16AC4VfLZaBQemEd1cCqBfFCdzsHEoMEd5yl9IAgwLv2zbeO4aArFf65hC9t/yMi9yR+6KumKUAaxNKpJylNEvumkO0LkX4VeGPXY0MSf73VAHg9D+yPRZLdT9/tk1qXdWewDMcRmdJZdYO4w+GZzbq/0Fn+0FGRDPtxUOOgwL1vgD7qWpUN8iVxwWWn2cZKvvPjBibpiKgxZZkg3cH5RSfTGVTUfcwR9YaiYsZTjGixoYZpHwUI6wk5kd4rsHwts2o+0=
   file: $RELEASE_PKG_FILE
   skip_cleanup: true
   on:
     tags: true
     condition: $TRAVIS_PYTHON_VERSION == 3.9
     repo: interfax/interfax-python
